on: ["push", "pull_request"]

name: Test Coveralls


jobs:
  coveralls:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 13}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel pytest coveralls

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: python -m pip install .
  
    
      - name: Test
        run: python -m pytest -cov=gfModParser --cov-report lcov


      - name: Coveralls
        uses: coverallsapp/github-action@v2
