name: Windows CI
on: [push, pull_request]
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux_ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]    
        python-version: ['3.10', '3.11', '3.12', '3.13']    
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}


    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          choco install make
          python -m pip install --upgrade pip==25.2
          python -m pip install build wheel

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: python -m pip install .[test]

  
      - name: Test
        run: python -m pytest -v

